### ISSUE TITLE
Please include architecture in AppImage name

### ISSUE THREAD

**Issue by probonopd** [LightouchDev/MasterVyrn#6]
`MasterVyrn-0.3.0-linux.AppImage` should be called `MasterVyrn-0.3.0-x86_64.AppImage` to make clear for which architecture it is. Thanks!

**Comment by miaulightouch** [comment]
Sorry, it's an upstream issue: electron-userland/electron-builder#2258

as it has been closed, next version of MasterVyrn would solve this issue.
